### ISSUE TITLE
Cファイルの文字をJSにインポートできるか？

### ISSUE THREAD

**Issue by kugimasa** [kugimasa/CodeTyper#17]
・全てを文字列に入れてインデントはどうするか？？

**Comment by kugimasa** [comment]
https://qiita.com/kazu56/items/557740f398e82fc881df
型判定などに使える？？

**Comment by kugimasa** [comment]
https://qiita.com/ue5963/items/bd8e32ac9e6b12aa7fab
. とか { とかはこれ...??
#正規表現判定とは

**Comment by kugimasa** [comment]
https://www.pazru.net/html5/File/020.html
一旦ファイルをテキストとしてインポート

**Comment by Yamakatsu63** [comment]
ファイルをテキスト化してインポートできました！
