### ISSUE TITLE
文字判定

### ISSUE THREAD

**Issue by kugimasa** [kugimasa/CodeTyper#18]
https://web-designer.cman.jp/javascript_ref/keyboard/keycode/
☝️有能サイトです

**Comment by Yamakatsu63** [comment]
文字入力のイベントを"keypress"にすることにより，Shiftキーを押したときの動作を区別することができるようになりました．
target.innerHTMLのメソッドを.innerTextにすることにより，<>を表示できるようになりました．

**Comment by Yamakatsu63** [comment]
改行の処理がわからない

**Comment by Yamakatsu63** [comment]
改行の処理，Tabキーの処理できました！
