### ISSUE TITLE
firebase関連

### ISSUE THREAD

**Issue by kugimasa** [kugimasa/CodeTyper#21]
http://blue-bear.jp/kb/javascript-firebasestorage%E3%81%AB%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E3%81%99%E3%82%8B/

ローカルファイルのアップロード

**Comment by kugimasa** [comment]
https://www.html5rocks.com/ja/tutorials/file/dndfiles/
ファイルをjsでアップロードする

**Comment by kugimasa** [comment]
アップロードは出来た‼︎

**Comment by Yamakatsu63** [comment]
https://developer.mozilla.org/ja/docs/Web/API/Document/createElement
jsにファイルを表示するときのタグの作り方

**Comment by kugimasa** [comment]
CORS??の導入をしました

**Comment by kugimasa** [comment]
RealtimeDBについて詳しく書かれた記事
https://qiita.com/seiya1121/items/4cbc32678558315c2159
