### ISSUE TITLE
タイムアタックの実装について

### ISSUE THREAD

**Issue by Yamakatsu63** [kugimasa/CodeTyper#34]
タイムアタック実装時にFirebaseからランダムに要素をとってくる方法がわかりません．

**Comment by kugimasa** [comment]
`dbRef.orderByValue("何か").limitToFirst(1)`とかでDBの要素並び替えてから要素一つだけを持ってくるとかかなぁ...??
orderByValue(),orderByKey(),orderByChild()でうまく並び替えたらできそう
https://firebase.google.com/docs/database/android/lists-of-data?hl=ja

**Comment by Yamakatsu63** [comment]
データベースの要素並び替えて、他のユーザが同時にメニュー画面開いたら並び替えられた順でコードが表示される？

**Comment by Yamakatsu63** [comment]
JSで例が書いてあるサイト
https://firebase.google.com/docs/database/web/retrieve-data?hl=ja

**Comment by kugimasa** [comment]
今DBのonメソッドでsnapshotとしてデータ取ってきてるんだけど
onメソッドがアクセスされたときに発火だから並び順変わるはず...？
